while continuer == 0:
    aDire = input("Que veux-tu me dire? : ")
if aDire == ("quand est né steve jobs"):
    print("le 24 février 1955, a San Fransisco, Californie, Etat Unis")
elif aDire == ("steve jobs")
  print("Steve Jobs est, avec Steve Wozniak, le cofondateur d’Apple. Ils sont tous deux considérés comme les pionniers de la micro-informatique pour avoir introduit l’ordinateur dans les foyers (bien avant l’avènement de l’IBM PC), puis pris conscience du potentiel du couple interface graphique / souris à la suite d’une visite avec une équipe de leur société au PARC de Xerox. Cette idée mènera à la commercialisation par la société Apple Computer du Macintosh, le premier ordinateur grand public profitant de ces innovations.Il est en 2009 la 43e fortune américaine.")
elif aDire == ("guernica")
  print("Guernica est un tableau de Pablo Picasso. Cette oeuvre d'art a été créée en réponse au bombardement de Guernica par l'aviation allemande et italienne, à la demande des forces espagnoles nationalistes, le 26 avril 1937, durant la guerre civile espagnole.")
elif aDire == ("résumé de eldorado")
  print("Le travail du commandant Salvatore Piracci consiste a intercepter les immigrants qui arrivent par bateau en Sicile. Ils sont clandestins et attendent tout de leur nouvelle vie. Un jour, une femme arrivée deux années plus tôt sur l'île le retrouve. Elle lui raconte dans quelles conditions elle a voyagé et comment elle a perdu son bébé qui était avec elle sur le bateau. Plus tard, un homme qui se trouvait dans un bateau de clandestins qu'il vient d' intercepter lui demande son aide. Le commandant refuse.")
elif aDire == ("bretagne")
  print("C'est un petit pays ayant été envahi par un pays capitaliste la France")
elif aDire == ("resume de pierre et jean")
  print("Les Roland , anciens bijoutiers parisiens se sont retirés au Havre, où ils vivent des jours heureux. Ils ont deux fils : l'aîné, Pierre, près de la trentaine, brun, maigre et nerveux, tourmenté par de grands projets et sujet à des découragements imprévus , vient d'obtenir son de terminer ses études de médecine.Les Roland , anciens bijoutiers parisiens se sont retirés au Havre, où ils vivent des jours heureux , ils ont deux fils : l aîné, Pierre, près de la trentaine, brun, maigre et nerveux, tourmenté par de grands projets et sujet à des découragements imprévus , vient d obtenir son de terminer ses études de médecine.")
elif aDire("resume de un monde sauvage")
  print("Felitsa accompagne régulièrement sa mère, garde forestier, dans ses inspections. Nous sommes au bout du bout de la taiga russe, la nature est sauvage et la vie difficile pour tous, humains comme animaux.  Des traces de tigre sont repérées, c'est un animal très convoité par les braconniers. Felitsa et sa mère arriveront-elles à sauver cette tigresse et ses petits ?")
elif aDire("")
  print("")
elif aDire("")
  print("")
elif aDire("")
  print("")
elif aDire("")
  print("")
elif aDire("")
  print("")
elif aDire("")
  print("")
elif aDire("")
  print("")
elif aDire("")
  print("")
elif aDire("")
  print("")
elif aDire("")
  print("")
elif aDire("")
  print("")
elif aDire("")
  print("")
elif aDire("")
  print("")
elif aDire("")
  print("")
elif aDire("")
  print("")
elif aDire("")
  print("")
elif aDire("")
  print("")
elif aDire("")
  print("")
elif aDire("")
  print("")
elif aDire("")
  print("")
elif aDire("")
  print("")    
elif aDire("")
  print("")
elif aDire("")
  print("")
else:
    print("je ne connais pas encore cela désolé")
