
    aDire = input("Que veux-tu me dire? : ")
if aDire == ("quand est né steve jobs"):
    print("le 24 février 1955, a San Fransisco, Californie, Etat Unis")
elif aDire == ("steve jobs")
  print("Steve Jobs est, avec Steve Wozniak, le cofondateur d’Apple. Ils sont tous deux considérés comme les pionniers de la micro-informatique pour avoir introduit l’ordinateur dans les foyers (bien avant l’avènement de l’IBM PC), puis pris conscience du potentiel du couple interface graphique / souris à la suite d’une visite avec une équipe de leur société au PARC de Xerox. Cette idée mènera à la commercialisation par la société Apple Computer du Macintosh, le premier ordinateur grand public profitant de ces innovations.Il est en 2009 la 43e fortune américaine.")
elif aDire == ("guernica")
  print("Guernica est un tableau de Pablo Picasso. Cette oeuvre d'art a été créée en réponse au bombardement de Guernica par l'aviation allemande et italienne, à la demande des forces espagnoles nationalistes, le 26 avril 1937, durant la guerre civile espagnole.")
elif aDire == ("résumé de eldorado")
  print("Le travail du commandant Salvatore Piracci consiste a intercepter les immigrants qui arrivent par bateau en Sicile. Ils sont clandestins et attendent tout de leur nouvelle vie. Un jour, une femme arrivée deux années plus tôt sur l'île le retrouve. Elle lui raconte dans quelles conditions elle a voyagé et comment elle a perdu son bébé qui était avec elle sur le bateau. Plus tard, un homme qui se trouvait dans un bateau de clandestins qu'il vient d' intercepter lui demande son aide. Le commandant refuse.")
elif aDire == ("bretagne")
  print("C'est un petit pays ayant été envahi par un pays capitaliste la France")
elif aDire == ("resume de pierre et jean")
  print("Les Roland , anciens bijoutiers parisiens se sont retirés au Havre, où ils vivent des jours heureux. Ils ont deux fils : l'aîné, Pierre, près de la trentaine, brun, maigre et nerveux, tourmenté par de grands projets et sujet à des découragements imprévus , vient d'obtenir son de terminer ses études de médecine.Les Roland , anciens bijoutiers parisiens se sont retirés au Havre, où ils vivent des jours heureux , ils ont deux fils : l aîné, Pierre, près de la trentaine, brun, maigre et nerveux, tourmenté par de grands projets et sujet à des découragements imprévus , vient d obtenir son de terminer ses études de médecine.")
elif aDire == ("resume de un monde sauvage")
  print("Felitsa accompagne régulièrement sa mère, garde forestier, dans ses inspections. Nous sommes au bout du bout de la taiga russe, la nature est sauvage et la vie difficile pour tous, humains comme animaux.  Des traces de tigre sont repérées, c'est un animal très convoité par les braconniers. Felitsa et sa mère arriveront-elles à sauver cette tigresse et ses petits ?")
elif aDire == ("tom cruise")
  print("un acteur et producteur américain, né le 3 juillet 1962 à Syracuse dans l'État de New York.Après avoir interprété des seconds rôles, notamment dans Taps et Outsiders, il obtient son premier rôle important dans la comédie dramatique Risky Business en 1983, mais c'est après avoir interprété Pete « Maverick » Mitchell dans Top Gun (1986) qu'il devient une star internationale. Depuis, il a joué dans de nombreux films à succès, tels que Rain Man, Né un 4 juillet, Entretien avec un vampire et les cinq épisodes de la saga Mission impossible. ")
elif aDire == ("brad pitt")
  print("William Bradley Pitt, dit Brad Pitt, est un acteur et producteur de cinéma américain né le 18 décembre 1963 à Shawnee (Oklahoma).Repéré dans une publicité pour Levi's, Brad Pitt sort de l'anonymat grâce à un petit rôle dans le film Thelma et Louise de Ridley Scott. En très peu de temps, il devient une véritable star et sa collaboration avec le réalisateur David Fincher donne naissance aux films cultes Seven, Fight Club et L'Étrange Histoire de Benjamin Button")
elif aDire == ("johnny depp")
  print("Johnny Depp est un acteur, réalisateur, guitariste, scénariste et producteur de cinéma américain, né le 9 juin 1963 à Owensboro, Kentucky. Il est devenu célèbre dans les années 1980 grâce à son rôle dans la série télévisée 21 Jump Street. Il a ensuite voulu se détacher de son image de jeune premier en se consacrant principalement à l'interprétation de personnages originaux et excentriques tels qu'Edward dans Edward aux mains d'argent, Raoul Duke (alter ego de l'écrivain Hunter S. Thompson) dans Las Vegas Parano, Ichabod Crane dans Sleepy Hollow, Jack Sparrow dans la saga Pirates des Caraïbes, le Chapelier fou dans Alice au pays des merveilles et Barnabas Collins dans Dark Shadows")
elif aDire == ("torvald")
  print("Linus Benedict Torvalds, né le 28 décembre 1969 à Helsinki en Finlande, est un informaticien américano-finlandais. Il est connu pour avoir créé en 1991 le noyau Linux dont il continue de diriger le développement.")
elif aDire == ("joconde")
  print("La Joconde, ou Portrait de Mona Lisa1, est un tableau de l'artiste italien Léonard de Vinci, réalisé entre 1503 et 1506, qui représente un portrait mi-corps, probablement celui de la florentine Lisa Gherardini, épouse de Francesco del Giocondo. Acquise par François Ier, cette peinture à l'huile sur panneau de bois de peuplier de 77 × 53 cm est exposée au musée du Louvre à Paris. La Joconde est l'un des rares tableaux attribués de façon certaine à Léonard de Vinci.")
elif aDire == ("le radeau de la meduse")
  print("Le Radeau de La Méduse est une peinture à l'huile sur toile, réalisée entre 1818 et 1819 par le peintre et lithographe romantique français Théodore Géricault (1791-1824). Son titre initial, donné par Géricault lors de sa première présentation, est Scène d'un naufrage. Ce tableau, de très grande dimension (491 cm de hauteur et 716 cm de largeur), représente un épisode tragique de l'histoire de la marine française : le naufrage de la frégate Méduse, qui s'échoue sur un banc de sable au large des côtes de l'actuelle Mauritanie, le 2 juillet 1816.")
elif aDire == ("la cene")
  print("La Cène (en italien : L'Ultima Cena, soit « le Dernier Repas ») de Léonard de Vinci est une peinture murale à la détrempe (tempera) de 460 × 880 cm, réalisée de 1494 à 1498 pour le réfectoire du couvent dominicain de Santa Maria delle Grazie à Milan, qui était considérée jusqu'au milieu du XIXe siècle comme son chef-d'œuvre.")
elif aDire == ("le cri")
  print("Le Cri (en norvégien : Skrik) est une œuvre expressionniste de l'artiste norvégien Edvard Munch dont il existe cinq versions (trois peintures, un pastel et une lithographie) réalisées entre 1893 et 1917. Symbolisant l'homme moderne emporté par une crise d'angoisse existentielle, elle est considérée comme l'œuvre la plus importante de l'artiste. Le paysage en arrière-plan est le fjord d'Oslo, vu d'Ekeberg. L'une des cinq versions a été vendue par Sotheby's à New York pour un montant de 119,9 millions de dollars. Elle détient ainsi, le 2 mai 2012, le record de vente d'une peinture aux enchères.")
elif aDire == ("l'etranger")
  print("L’Étranger est le premier roman d’Albert Camus, paru en 1942. Il prend place dans la tétralogie que Camus nommera « cycle de l’absurde » qui décrit les fondements de la philosophie camusienne : l’absurde. Cette tétralogie comprend également l’essai intitulé Le Mythe de Sisyphe ainsi que les pièces de théâtre Caligula et Le Malentendu. Le roman a été traduit en quarante langues et une adaptation cinématographique en a été réalisée par Luchino Visconti en 1967.")
elif aDire == ("la villa savoye")
  print("La villa Savoye est une villa construite de 1928 à 1931 par l'architecte Le Corbusier, sur la commune française de Poissy, dans les Yvelines.")
elif aDire == ("la cité radieuse")
  print("L'unité d'habitation de Marseille connue sous le nom de Cité radieuse, « Le Corbusier » ou plus familièrement « La Maison du fada » , est une résidence édifiée entre 1947 et 1952 par l'architecte Le Corbusier (280 boulevard Michelet, 8e arrondissement de Marseille). Bâtie sous forme de barre sur pilotis (en forme de piètements évasés à l'aspect brutaliste) elle tente de concrétiser une nouvelle forme de cité, un « village vertical » appelé « Unité d'habitation ».")
elif aDire == ("breizh brezel")
  print("Le conflit entre le duché de Bretagne et le royaume de France se décline en une succession d'épisodes militaires et diplomatiques entre 1465 et 1491, date du mariage entre Anne de Bretagne et Charles VIII de France. Il aboutira par la suite à la fin de l'indépendance de la Bretagne.Ce conflit fait suite à la guerre de Succession de Bretagne, lors de laquelle deux partis, un pro-anglais et un pro-français, s'étaient affrontés entre 1341 et 1364.")
elif aDire == ("trump")
  print("désolé , mais ce nom n'existe plus ou a été  exterminer!")
elif aDire == ("donald")
  print("Donald Fauntleroy Duck, ou simplement Donald Duck, est un personnage de fiction développé, entre autres, par l'animateur Dick Lundy")
elif aDire == ("porte contenaire")
  print("Un porte-conteneurs est un navire destiné au transport de conteneurs à l'exclusion de tout autre type de marchandises. Apparu dans les années 1970, le porte-conteneurs est maintenant le principal mode de transport maritime de fret dans les ports de commerce. Il fait partie intégrante du commerce mondial. Leur taille sans cesse croissante crée de nombreux problèmes architecturaux et portuaires.")
elif aDire == ("tom hanks")
  print("Thomas Jeffrey Hanks dit Tom Hanks, né le 9 juillet 1956 à Concord (Californie), est un acteur, réalisateur et producteur de cinéma américain.Il est devenu célèbre avec le film Splash, avant de connaître la consécration avec Philadelphia et Forrest Gump, qui lui valurent chacun l'Oscar du meilleur acteur. La quasi-totalité de ses films suivants furent des grands succès, comme Apollo 13, Il faut sauver le soldat Ryan et La Ligne verte. Il est souvent comparé à James Stewart, et son talent reconnu lui a permis de devenir l'un des acteurs fétiches des réalisateurs Steven Spielberg, Robert Zemeckis et Ron Howard.")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")    
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")    
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")    
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")    
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")    
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")    
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")    
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")    
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")    
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")    
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")    
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")    
elif aDire == ("")
  print("")
elif aDire == ("")
  print("")
else:
    print("je ne connais pas encore cela désolé")
